use customer_behavior;
select * from customer limit 20;

# 1- what is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

# 2- Which customers use a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

# 3- Which are the top 5 product with the highest average review rating?

select item_purchased , round(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

# 4- Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type,
round(AVG(puchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type; 